[package]

name          = "mio-more"
version       = "0.1.0"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Extra components for use with Mio"
documentation = "https://docs.rs/mio-more"
homepage      = "https://github.com/carllerche/mio-more"
repository    = "https://github.com/carllerche/mio-more"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
categories    = ["asynchronous"]
exclude       = [
  ".gitignore",
  ".travis.yml",
]

[dependencies]
mio = "0.6"
log = "0.3.1"
lazycell = "0.4.0"
slab = "0.3.0"
